# Generated by Django 2.0.3 on 2018-04-08 10:18

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('value', models.CharField(max_length=128, verbose_name='value')),
                ('alert_type', models.PositiveIntegerField(choices=[(1, 'Phone'), (2, 'Cell'), (3, 'Pager'), (4, 'Fax'), (5, 'Email')])),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('remote_id', models.IntegerField()),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='middle name')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='title')),
                ('prefix', models.CharField(blank=True, max_length=24, null=True, verbose_name='prefix')),
                ('suffix', models.CharField(blank=True, max_length=24, null=True, verbose_name='suffix')),
                ('preferred_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='preferred name')),
                ('phone', models.IntegerField(null=True, verbose_name='phone')),
                ('cell', models.IntegerField(blank=True, null=True, verbose_name='cell')),
                ('pager', models.IntegerField(blank=True, null=True, verbose_name='pager')),
                ('fax', models.IntegerField(blank=True, null=True, verbose_name='fax')),
                ('preferred_mode', models.PositiveIntegerField(blank=True, choices=[(1, 'Phone'), (2, 'Cell'), (3, 'Pager'), (4, 'Fax'), (5, 'Email')], null=True)),
                ('hospital_department', models.CharField(max_length=255, verbose_name='hospital department')),
                ('hospital_role', models.CharField(max_length=128, verbose_name='hospital role')),
            ],
            options={
                'verbose_name': 'user',
                'abstract': False,
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAlertSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert1', to='accounts.AlertMethod')),
                ('alert2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert2', to='accounts.AlertMethod')),
                ('alert3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert3', to='accounts.AlertMethod')),
                ('alert4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert4', to='accounts.AlertMethod')),
                ('doctor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('remote_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'user',
                'abstract': False,
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SignOutLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('sign_out', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor')),
            ],
            options={
                'ordering': ['sign_out'],
            },
        ),
        migrations.AddField(
            model_name='alertmethod',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor'),
        ),
    ]
