# Generated by Django 2.0.3 on 2018-04-10 20:17

from django.db import migrations, models
import django.db.models.deletion
import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='doctor',
            managers=[
                ('objects', accounts.models.UserSoftDeleteModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='patient',
            managers=[
                ('objects', accounts.models.UserSoftDeleteModelManager()),
            ],
        ),
        migrations.AlterField(
            model_name='doctoralertsetting',
            name='doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_settings', to='accounts.Doctor'),
        ),
    ]
