# Generated by Django 2.0.3 on 2018-04-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180410_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cell',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cell'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='fax'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='pager',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='pager'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='phone'),
        ),
    ]
