# Generated by Django 2.0.3 on 2018-04-18 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180417_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_remote_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='clinic remote ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='title')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='title')),
                ('remote_role', models.PositiveIntegerField(choices=[(1, 'Hospital Admin'), (2, 'Doctor'), (3, 'Nurse')], default=3)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Hospital')),
            ],
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'doctor', 'verbose_name_plural': 'doctors'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.HospitalDepartment'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.HospitalRole'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Hospital'),
        ),
    ]
