# Generated by Django 2.0.3 on 2018-04-23 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180420_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmethod',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 12, 37, 6, 858599, tzinfo=utc)),
        ),
    ]
