# Generated by Django 2.0.3 on 2018-04-24 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180424_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertmethod',
            old_name='bind_field',
            new_name='index_number',
        ),
        migrations.AlterField(
            model_name='alertmethod',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 24, 7, 58, 56, 215681, tzinfo=utc)),
        ),
    ]
