# Generated by Django 2.0.3 on 2018-04-24 07:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180424_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmethod',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 24, 7, 59, 4, 965858, tzinfo=utc)),
        ),
    ]
