# Generated by Django 2.0.3 on 2018-04-24 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180424_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmethod',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 24, 9, 23, 14, 641354, tzinfo=utc)),
        ),
    ]
