# Generated by Django 2.0.3 on 2018-04-24 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180424_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmethod',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 24, 12, 2, 38, 345872, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Hospital'),
        ),
    ]
