# Generated by Django 2.0.3 on 2018-04-24 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180424_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmethod',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
