# Generated by Django 2.0.3 on 2018-04-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180424_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'patient', 'verbose_name_plural': 'patients'},
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='patient',
            name='encounter_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='fax'),
        ),
        migrations.AddField(
            model_name='patient',
            name='guarantor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='guarantor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='insurance'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pager',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='pager'),
        ),
        migrations.AddField(
            model_name='patient',
            name='power_of_attorney',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='power of attorney'),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='preferred name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='prefix',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='prefix'),
        ),
        migrations.AddField(
            model_name='patient',
            name='room_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='patient',
            name='suffix',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='suffix'),
        ),
        migrations.AddField(
            model_name='patient',
            name='title',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
