# Generated by Django 2.0.3 on 2018-04-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180424_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertmethod',
            options={'ordering': ['-last_update']},
        ),
        migrations.RemoveField(
            model_name='alertmethod',
            name='created_time',
        ),
        migrations.AddField(
            model_name='alertmethod',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='alertmethod',
            name='index_number',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unset'), (1, 'Alert1'), (2, 'Alert2'), (3, 'Alert3'), (4, 'Alert4')], default=0, null=True),
        ),
    ]
