# Generated by Django 2.0.3 on 2018-05-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180430_1200'),
        ('accounts', '0014_auto_20180430_0628'),
    ]

    operations = [
    ]
