# Generated by Django 2.0.3 on 2018-05-08 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180507_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='dea_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DEA Number'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='npi_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NPI Number'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='state_license',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='State license'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='User id'),
        ),
    ]
