# Generated by Django 2.0.3 on 2018-05-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180508_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
