# Generated by Django 2.0.3 on 2018-05-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180508_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
