# Generated by Django 2.0.3 on 2018-05-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20180515_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuffList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor')),
                ('participants', models.ManyToManyField(related_name='stuff_participants', to='accounts.Doctor')),
            ],
        ),
    ]
