# Generated by Django 2.0.3 on 2018-05-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_stufflist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stufflist',
            name='owner',
        ),
    ]
