# Generated by Django 2.0.3 on 2018-06-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_stufflist_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertmethod',
            name='list_index',
        ),
    ]
