# Generated by Django 2.0.3 on 2018-06-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alertmethod_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='create_data_cell_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='edit_data_cell_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='export_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='patient_permission',
            field=models.BooleanField(default=False),
        ),
    ]
