# Generated by Django 2.0.3 on 2018-06-11 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20180608_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='clinic_remote_admin_password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hospital',
            name='clinic_remote_admin_username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='stufflist',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='accounts.Hospital'),
        ),
    ]
