# Generated by Django 2.0.3 on 2018-06-14 10:01

from django.db import migrations


def delete_duplicate_stuff_list(apps, shema_editor):
    StuffList = apps.get_model('accounts', 'StuffList')
    for stuff_list in StuffList.objects.all():
        if StuffList.objects.filter(title=stuff_list.title).count() > 1:
            stuff_list.delete()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0026_auto_20180611_0421'),
    ]

    operations = [
        migrations.RunPython(delete_duplicate_stuff_list, reverse),
    ]
