# Generated by Django 2.0.3 on 2018-06-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20180614_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stufflist',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
