# Generated by Django 2.0.3 on 2018-06-14 11:40

from django.db import migrations


def delete_duplicate_alerts(apps, shema_editor):
    AlertMethod = apps.get_model('accounts', 'AlertMethod')
    for stuff_list in AlertMethod.objects.all():
        if AlertMethod.objects.filter(title=stuff_list.title).count() > 1:
            stuff_list.delete()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0028_auto_20180614_0525'),
    ]

    operations = [
        migrations.RunPython(delete_duplicate_alerts, reverse)
    ]
