# Generated by Django 2.0.3 on 2018-06-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20180614_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmethod',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='title'),
        ),
    ]
