# Generated by Django 2.0.3 on 2018-06-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20180614_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmethod',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='stufflist',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='alertmethod',
            unique_together={('title', 'doctor')},
        ),
        migrations.AlterUniqueTogether(
            name='stufflist',
            unique_together={('title', 'hospital')},
        ),
    ]
