# Generated by Django 2.0.3 on 2018-06-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20180622_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guarantor',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
    ]
