# Generated by Django 2.0.3 on 2018-06-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20180625_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='zip_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
