# Generated by Django 2.0.3 on 2018-06-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20180625_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='address',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='guarantor',
            old_name='address',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='address2',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='address3',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='address2',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='address3',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address2',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address3',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pcp',
            field=models.TextField(blank=True, null=True, verbose_name='pcp'),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_pharmacy',
            field=models.TextField(blank=True, null=True, verbose_name='preferred pharmacy'),
        ),
    ]
