# Generated by Django 2.0.3 on 2018-06-26 16:43

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20180626_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doctor_fk',
            new_name='responsible_doctor',
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='ssn',
            field=models.CharField(error_messages={'unique': 'A patient with that ssn already exists.'}, help_text='format XXX-XX-XXXX where X - number', max_length=150, null=True, validators=[accounts.utils.SsnValidator()], verbose_name='ssn'),
        ),
    ]
