# Generated by Django 2.0.3 on 2018-07-09 13:33

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20180703_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ssn',
            field=models.CharField(error_messages={'unique': 'A patient with that ssn already exists.'}, help_text='format XXX-XX-XXXX where X - number', max_length=150, null=True, validators=[accounts.utils.SsnValidator()], verbose_name='ssn'),
        ),
    ]
