# Generated by Django 2.0.3 on 2018-07-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20180709_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='my_patients_list_participants',
            field=models.ManyToManyField(related_name='my_list_participants', to='accounts.DoctorPatient'),
        ),
    ]
