# Generated by Django 2.0.3 on 2018-07-13 11:25

from django.db import migrations, models
import django.db.models.deletion


def set_default_value(apps, schema_editor):
    Patient = apps.get_model('accounts', 'Patient')
    Doctor = apps.get_model('accounts', 'Doctor')
    first_doctor = Doctor.objects.first()
    for pat in Patient.objects.all():
        pat.responsible_doctor = first_doctor
        pat.save()


def reverse_default_value(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0040_doctor_my_patients_list_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvImportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.PositiveSmallIntegerField(choices=[(1, 'Patient'), (2, 'Doctor')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed', models.SmallIntegerField()),
                ('added', models.SmallIntegerField()),
                ('errors', models.SmallIntegerField()),
                ('sheet', models.FileField(upload_to='uploads/import/%Y-%m-%d/')),
                ('author',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_imports',
                                   to='accounts.Doctor')),
            ],
            options={
                'ordering': ['import_type', '-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='patient',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='patient',
            name='responsible_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients',
                                    to='accounts.Doctor'),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_value, reverse_default_value),
        migrations.AlterField(
            model_name='patient',
            name='responsible_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients',
                                    to='accounts.Doctor'),
            preserve_default=False,
        ),
    ]
