# Generated by Django 2.0.3 on 2018-07-23 07:31

from django.db import migrations


def delete_wrong_patients_list(apps, schema_editor):
    PatientsList = apps.get_model('accounts', 'PatientsList')
    for pat_list in PatientsList.objects.all():
        if [patient.remote_id for patient in pat_list.participants.all() if
                patient.responsible_doctor.hospital != pat_list.hospital]:
            pat_list.delete()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0041_auto_20180713_0625'),
    ]

    operations = [
        migrations.RunPython(delete_wrong_patients_list, reverse)
    ]
