# Generated by Django 2.0.3 on 2018-07-26 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20180723_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientslist',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Hospital'),
        ),
    ]
