# Generated by Django 2.0.3 on 2018-08-07 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('accounts', '0043_auto_20180726_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hidden_doctor_home_column_list',
            field=models.ManyToManyField(blank=True, null=True, to='home.DoctorHomeColumn'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='my_patients_list_participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_list_participants', to='accounts.DoctorPatient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='responsible_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='accounts.Doctor'),
        ),
    ]
