# Generated by Django 2.0.3 on 2018-08-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20180807_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hidden_doctor_home_column_list',
            field=models.ManyToManyField(blank=True, to='home.DoctorHomeColumn'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='my_patients_list_participants',
            field=models.ManyToManyField(blank=True, related_name='my_list_participants', to='accounts.DoctorPatient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='preferred_communication',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Phone'), (2, 'Cell'), (3, 'Pager'), (4, 'Fax'), (5, 'Email')], default=1),
        ),
    ]
