# Generated by Django 2.0.3 on 2018-08-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20180815_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='patient_order',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ascending'), (2, 'Descending')], default=1),
        ),
        migrations.AddField(
            model_name='doctor',
            name='patient_sort_by',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SSN'), (2, 'First name'), (3, 'Last name'), (4, 'DOB')], default=1),
        ),
    ]
