# Generated by Django 2.0.3 on 2018-08-30 15:20

from django.db import migrations


def fill_patient_hospital(apps, shema_editor):
    Patient = apps.get_model('accounts', 'Patient')
    hospital = apps.get_model('accounts', 'Hospital').objects.all()
    if not hospital:
        return
    else:
        hospital = hospital.first()
    for patient in Patient.objects.all():
        if patient.responsible_doctor and patient.responsible_doctor.hospital:
            patient.hospital = patient.responsible_doctor.hospital
        else:
            patient.hospital = hospital
        patient.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0047_auto_20180830_1012'),
    ]

    operations = [
        migrations.RunPython(fill_patient_hospital, reverse),
    ]
