# Generated by Django 2.0.3 on 2018-08-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20180830_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='responsible_doctor',
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='city'),
        ),
    ]
