# Generated by Django 2.0.3 on 2018-09-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20180907_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
