# Generated by Django 2.0.3 on 2018-10-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_patient_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patient_sort_by',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SSN'), (2, 'First name'), (3, 'Last name'), (4, 'DOB'), (5, 'ROOM')], default=1),
        ),
    ]
