# Generated by Django 2.0.3 on 2018-04-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webnotification',
            options={'ordering': ['-created_at']},
        ),
    ]
