# Generated by Django 2.0.3 on 2018-05-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20180430_0421'),
        ('notifications', '0002_auto_20180430_0928'),
    ]

    operations = [
    ]
