# Generated by Django 2.0.3 on 2018-05-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_merge_20180503_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webnotification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.Doctor'),
        ),
    ]
