# Generated by Django 2.0.3 on 2018-07-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20180516_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.PositiveSmallIntegerField(choices=[(1, 'New User Account Is Ready')], unique=True)),
                ('subject_message', models.CharField(max_length=255)),
                ('html_message', models.TextField()),
            ],
        ),
    ]
