# Generated by Django 2.0.3 on 2018-07-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20180710_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New User Account Is Ready'), (2, 'New Message In IDR'), (3, 'New User Was Registered'), (4, 'Account Was Activated'), (5, 'Account Was Declined'), (6, 'Your Password Was Changed')], unique=True),
        ),
    ]
