# Generated by Django 2.0.3 on 2018-07-17 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20180713_0625'),
        ('notifications', '0013_auto_20180716_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_creator', to='accounts.Doctor')),
                ('participants', models.ManyToManyField(related_name='chat_participants', to='accounts.Doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
                ('attachment', models.FileField(blank=True, max_length=200, null=True, upload_to='uploads/notification_attachments/%Y-%m-%d/')),
                ('urgency', models.PositiveIntegerField(choices=[(1, 'Immediate'), (2, '30 minutes'), (3, '1hr'), (4, '2hr'), (5, 'FYI - No Alert')], default=5)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_edit', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.Chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.Doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='webnotification',
            name='doctor_receivers',
        ),
        migrations.RemoveField(
            model_name='webnotification',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='webnotification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='webreceivernotification',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='webreceivernotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='WebNotification',
        ),
        migrations.DeleteModel(
            name='WebReceiverNotification',
        ),
    ]
