# Generated by Django 2.0.3 on 2018-07-31 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20180726_0728'),
        ('notifications', '0014_auto_20180717_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatIsDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.Chat')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='MessageIsDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='messageisdelete',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.Message'),
        ),
    ]
