# Generated by Django 2.0.3 on 2018-08-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_auto_20180731_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
