# Generated by Django 2.0.3 on 2018-08-17 12:53

from django.db import migrations
from accounts.utils import get_patients_cache


def set_chat_patient_name(apps, schema_editor):
    Chat = apps.get_model('notifications', 'Chat')
    for ch in Chat.objects.all():
        if ch.patient:
            remote_patient = get_patients_cache(hospital=ch.patient.responsible_doctor.hospital).get(
                'patients', {}).get(ch.patient.remote_id, {})
            ch.patient_name = remote_patient.get("first_name") + ' ' + remote_patient.get("last_name")
            ch.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0016_chat_patient_name'),
    ]

    operations = [
        migrations.RunPython(set_chat_patient_name, reverse)
    ]
