# Generated by Django 2.0.3 on 2018-08-06 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0043_auto_20180726_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorHomeCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('is_deleted', models.BooleanField(default=False)),
                ('update_interval', models.PositiveIntegerField(blank=True, choices=[(1, 'Immediate'), (2, '30 minutes'), (3, '1hr'), (4, '2hr'), (5, 'FYI - No Alert')], null=True)),
                ('column_group_id', models.PositiveIntegerField()),
                ('is_private', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorHomeCellField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('is_deleted', models.BooleanField(default=False)),
                ('value', models.TextField(max_length=5000, verbose_name='value')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='home.DoctorHomeCell')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorHomeColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('is_deleted', models.BooleanField(default=False)),
                ('update_interval', models.PositiveIntegerField(choices=[(1, 'Immediate'), (2, '30 minutes'), (3, '1hr'), (4, '2hr'), (5, 'FYI - No Alert')], default=5)),
                ('group_id', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor')),
            ],
            options={
                'ordering': ['group_id', 'id'],
            },
        ),
    ]
