# Generated by Django 2.0.3 on 2018-08-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorhomecell',
            name='update_interval',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '15min'), (2, '30min'), (3, '45min'), (4, '1hr'), (5, '2hrs'), (6, '3hrs'), (7, '4hrs'), (8, '5hrs'), (9, '6hrs'), (10, '7hrs'), (11, '8hrs'), (12, '9hrs'), (13, '10hrs'), (14, '11hrs'), (15, '12hrs'), (16, 'Daily'), (17, 'PRN'), (18, 'Never Alert')], null=True),
        ),
        migrations.AlterField(
            model_name='doctorhomecolumn',
            name='update_interval',
            field=models.PositiveIntegerField(choices=[(1, '15min'), (2, '30min'), (3, '45min'), (4, '1hr'), (5, '2hrs'), (6, '3hrs'), (7, '4hrs'), (8, '5hrs'), (9, '6hrs'), (10, '7hrs'), (11, '8hrs'), (12, '9hrs'), (13, '10hrs'), (14, '11hrs'), (15, '12hrs'), (16, 'Daily'), (17, 'PRN'), (18, 'Never Alert')], default=18),
        ),
    ]
