# Generated by Django 2.0.3 on 2018-08-15 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20180815_1338'),
        ('home', '0002_auto_20180813_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorHomeColumnOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.DoctorHomeColumn')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='doctorhomecolumnorder',
            unique_together={('doctor', 'column')},
        ),
    ]
