"""
Django settings for idr project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7pcz(-!i%4sb0d0j^*vf!%a5*vfhmjkred1#sc@u@xsvu)2j03'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

DJANGO_APPS = [
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

IDR_APPS = [
    'api',
    'accounts',
    'notifications',
    'home'
]

PROJ_APPS = [
    'rest_framework',
    'django_filters',
    'corsheaders',
    'celery',
    'django_celery_beat',
    'channels',
    # 'silk'

]

INSTALLED_APPS = DJANGO_APPS + IDR_APPS + PROJ_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'silk.middleware.SilkyMiddleware',
]

ROOT_URLCONF = 'idr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'idr.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'
DATE_INPUT_FORMATS = ('%m-%d-%Y', '%Y-%m-%d')
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

# How long till APIv1 Token Expires in Seconds
API_TOKEN_EXPIRE = 30 * 60

REST_FRAMEWORK = {
    # 'DATETIME_FORMAT': "%Y-%m-%d %H:%M:%S %z",
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'api.v1.authentication.ExpiringTokenAuthentication',

    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter'
    ),
    'PAGINATE_BY': 10,
    'PAGINATE_BY_PARAM': 'page_size',
    'MAX_PAGINATE_BY': 100,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    )
}

CORS_ORIGIN_WHITELIST = (
    'idr-frontend.staging.myappworx.com',
    'idr-auth.staging.myappworx.com',
    'idr.staging.myappworx.com',
)

CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'enctype'
)

BASE_URL = 'idr-frontend.staging.myappworx.com'
FROM_EMAIL = "noreply@myappworx.com"

TWILIO_ACCOUNT_SID = 'AC746507d53b179fd067cef5f3f2b48094'
TWILIO_AUTH_TOKEN = 'cff59b942ac3ceb5878190e9cc459837'

TWILIO_PHONE_NUMBER = "+18315316170"

PHONE_COUNTRY_PREFIX = "+1"

CELERY_BROKER_URL = 'redis://localhost:6379/0'

TEN_MINUTES = 60 * 10
THIRTY_MINUTES = 60 * 30
ONE_HOUR = 60 * 60
TWO_HOUR = 60 * 60 * 2

IDR_CLINIC_REMOTE_ID = 1
IDR_AUTH_GATEWAY_URL = "http://idr-auth.staging.myappworx.com"
IDR_AUTH_URL = IDR_AUTH_GATEWAY_URL + '/api/v2/authenticate/doctor/'
IDR_AUTH_LOGOUT_URL = IDR_AUTH_GATEWAY_URL + '/api/v2/authenticate/logout/'
IDR_AUTH_DOCTOR_URL = IDR_AUTH_GATEWAY_URL + '/api/v2/doctor/'
IDR_AUTH_PATIENT_URL = IDR_AUTH_GATEWAY_URL + '/api/v2/patient/'
IDR_AUTH_CHECK_EMAIL = IDR_AUTH_GATEWAY_URL + '/api/v2/checkemail/'
IDR_AUTH_CHECK_USERNAME = IDR_AUTH_GATEWAY_URL + '/api/v2/check-username/'

IDR_DOMAIN_NAME = 'IDR'
IDR_SITE_URL = 'http://idr-frontend.staging.myappworx.com/'

ASGI_APPLICATION = 'idr.routing.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [CELERY_BROKER_URL]
        },
    },
}
try:
    from .local_settings import *
except ImportError:
    pass
